package com.employee.dtotest;

import org.junit.jupiter.api.Test;

import com.employee.dto.PunchDto;

import java.time.LocalTime;

import static org.junit.jupiter.api.Assertions.*;

class PunchDtoTest {

    @Test
    void testGettersAndSetters() {
        PunchDto punchDto = new PunchDto();

        Long employeeId = 123L;
        LocalTime punchTime = LocalTime.of(9, 30, 0);

        punchDto.setEmployeeId(employeeId);
        punchDto.setTime(punchTime);

        assertEquals(employeeId, punchDto.getEmployeeId());
        assertEquals(punchTime, punchDto.getTime());
    }

    @Test
    void testConstructorAndToString() {
        Long employeeId = 456L;
        LocalTime punchTime = LocalTime.of(17, 45, 0);

        PunchDto punchDto = new PunchDto();
        punchDto.setEmployeeId(employeeId);
        punchDto.setTime(punchTime);

        // Just a sanity check on toString (generated by lombok)
        String toString = punchDto.toString();
        assertTrue(toString.contains(employeeId.toString()));
        assertTrue(toString.contains(punchTime.toString()));
    }
}
